# Generated by Django 3.0 on 2019-12-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191217_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='file',
            field=models.FileField(default='defaultFile', upload_to='whatever'),
            preserve_default=False,
        ),
    ]
