# Generated by Django 3.0 on 2019-12-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_usuario_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='file',
            field=models.FileField(upload_to='uploadedFiles'),
        ),
    ]
